# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.pharmacie_localisation import PharmacieLocalisation  # noqa: F401,E501
from swagger_server.models.pharmacie_produit import PharmacieProduit  # noqa: F401,E501
from swagger_server import util


class Pharmacie(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, nom: str=None, ifu: str=None, tel: int=None, localisation: PharmacieLocalisation=None, produit: List[PharmacieProduit]=None):  # noqa: E501
        """Pharmacie - a model defined in Swagger

        :param id: The id of this Pharmacie.  # noqa: E501
        :type id: str
        :param nom: The nom of this Pharmacie.  # noqa: E501
        :type nom: str
        :param ifu: The ifu of this Pharmacie.  # noqa: E501
        :type ifu: str
        :param tel: The tel of this Pharmacie.  # noqa: E501
        :type tel: int
        :param localisation: The localisation of this Pharmacie.  # noqa: E501
        :type localisation: PharmacieLocalisation
        :param produit: The produit of this Pharmacie.  # noqa: E501
        :type produit: List[PharmacieProduit]
        """
        self.swagger_types = {
            'id': str,
            'nom': str,
            'ifu': str,
            'tel': int,
            'localisation': PharmacieLocalisation,
           
        }

        self.attribute_map = {
            'id': '_id',
            'nom': 'nom',
            'ifu': 'ifu',
            'tel': 'tel',
            'localisation': 'localisation',
           
        }
        self._id = id
        self._nom = nom
        self._ifu = ifu
        self._tel = tel
        self._localisation = localisation
      

    @classmethod
    def from_dict(cls, dikt) -> 'Pharmacie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pharmacie of this Pharmacie.  # noqa: E501
        :rtype: Pharmacie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Pharmacie.


        :return: The id of this Pharmacie.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Pharmacie.


        :param id: The id of this Pharmacie.
        :type id: str
        """

        self._id = id

    @property
    def nom(self) -> str:
        """Gets the nom of this Pharmacie.


        :return: The nom of this Pharmacie.
        :rtype: str
        """
        return self._nom

    @nom.setter
    def nom(self, nom: str):
        """Sets the nom of this Pharmacie.


        :param nom: The nom of this Pharmacie.
        :type nom: str
        """

        self._nom = nom

    @property
    def ifu(self) -> str:
        """Gets the ifu of this Pharmacie.


        :return: The ifu of this Pharmacie.
        :rtype: str
        """
        return self._ifu

    @ifu.setter
    def ifu(self, ifu: str):
        """Sets the ifu of this Pharmacie.


        :param ifu: The ifu of this Pharmacie.
        :type ifu: str
        """

        self._ifu = ifu

    @property
    def tel(self) -> int:
        """Gets the tel of this Pharmacie.


        :return: The tel of this Pharmacie.
        :rtype: int
        """
        return self._tel

    @tel.setter
    def tel(self, tel: int):
        """Sets the tel of this Pharmacie.


        :param tel: The tel of this Pharmacie.
        :type tel: int
        """

        self._tel = tel

    @property
    def localisation(self) -> PharmacieLocalisation:
        """Gets the localisation of this Pharmacie.


        :return: The localisation of this Pharmacie.
        :rtype: PharmacieLocalisation
        """
        return self._localisation

    @localisation.setter
    def localisation(self, localisation: PharmacieLocalisation):
        """Sets the localisation of this Pharmacie.


        :param localisation: The localisation of this Pharmacie.
        :type localisation: PharmacieLocalisation
        """

        self._localisation = localisation

   
